<?php
// 电脑端路由

// 首页
Route::get('/', 'WebController@index');
// 游记
Route::resource('home/travel', 'TravelController')->names('home.travel');
// 会员中心
Route::get('home', 'TravelController@index')->name('home');
Route::view('home/setting', 'www.home.setting')->name('home.setting')->middleware('auth');
Route::get('home/order', 'HomeController@order')->name('home.order');
Route::get('home/order/{order}/show', 'HomeController@orderInfo')->name('home.order.show');
Route::view('home/order/info', 'www.home.order_info')->name('home.order.info')->middleware('auth');
Route::get('home/message', 'HomeController@message')->name('home.message');
Route::delete('home/message', 'HomeController@destroyMessages')->name('user.message.destroy');
Route::put('home/message', 'HomeController@readMessages')->name('user.message.read');
// 定制游
Route::view('customized', 'www.customized');
// 活动
Route::get('activity/show/{activity}', 'ShowController@activity')->name('activity.show');
Route::get('activity/list', 'ListController@activity')->name('activity.list');
// 攻略
Route::get('raider/show/{raider}', 'ShowController@raider')->name('raider.show');
Route::get('raider/list', 'ListController@raiders')->name('raider.list');
// 领队
Route::get('leader/show/{leader}', 'ShowController@leader')->name('leader.show');
Route::get('leader/list/{province?}', 'ListController@leaders')->name('leader.list');
// 游记
Route::get('travel/show/{travel}', 'ShowController@travel')->name('travel.show');
Route::get('travel/list', 'ListController@travel')->name('travel.list');
// 用户的游记列表
Route::get('travel/list/{user}', 'ListController@userTravel')->name('user.travel');
// 视频
Route::get('video/show/{video}', 'ShowController@video')->name('video.show');
Route::get('video/list', 'ListController@video')->name('video.list');
// 文章
Route::get('article/show/{article}', 'ShowController@article')->name('article.show');
// 搜索
Route::get('search', 'ListController@search')->name('search');
// 报名页面
Route::get('tuan/{tuan}', 'PayController@create')->name('pay.order.create');
// 生成微信订单
Route::get('pay/wechat/{order}', 'PayController@wechat')->name('pay.wechat');
// 生成支付宝订单 二维码
Route::get('pay/alipay/{order}', 'PayController@alipay')->name('pay.alipay');
// 显示二维码的支付页面和支付结果
Route::get('order/pay/{order}', 'PayController@showQrcode')->name('order.qrcode');
